### ISSUE TITLE
Pause script when playback paused

### ISSUE THREAD

**Issue by Sheugel** [pomle/spotify-prettydress#1]
Hi,
Thanks for this great app. I'm using it with my last.fm api key and loving it.
Would you consider implementing a pause of the script when the playback is paused because it´s quite resource consuming.
Thanks,
Sheugel

**Comment by pomle** [comment]
Sounds like a good idea. I would guess that stopping the zoom-effect should be good enough to relieve the CPU. However, the Chromium Embedded Framework is due for an update soon, which should contain GPU acceleration. I'd like to see how that works out before.
